Enhancement: Adding PhilipsHue Integration
EPMatt/awesome-ha-blueprints pull request #151
Opened 2021-10-03 10:04 UTC by krys1976

Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Breaking change

If your PR contains a breaking change for existing users, it is important to describe what breaks, how to make it work again and why we did this. This section will be used to craft the changelog entry, after your PR gets approved and merged.

Note: Remove this section if this PR is NOT a breaking change.

## Proposed change\*

This closes feature request #150 

## Checklist\*

- [X] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [X] I properly tested proposed changes on my system and confirm that they are working as expected.
- [ ] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

2021-12-05 23:09 UTC, EPMatt requested changes
Hi @krys1976,

thank you so much for your precious contribution! 🚀
 
I'm sorry for my late response. Today I rebased your PR and reviewed your work. I've added a few comments here with changes I think we should address before merging.

Moreover, this is a list of tasks I think we should consider before making updates available to the public:

1. Controller naming: I think we should use a more descriptive name for the `Friends of Hue` controller. The current pattern for naming controllers is `[Manufacturer] [Model no.] [Model name]`. Could you please rename the controller blueprint and all references to the controller in the hooks as well? 
2. Add a documentation page for the Friends of Hue controller
3. Update documentation pages (changelog, requirements & inputs) and blueprint versions for Philips 324131092621 and Philips 8718699693985 
4. Update documentation pages (changelog & new supported controller) and blueprint versions for the Light, Cover and Media Player hooks
5. Update the list of supported controllers. This includes also adding an image for the new device

This is quite a large amount of work, but I'd be happy to help you as I can in finalizing your contribution;  just let me know which tasks I can work on, and I'd be glad to help with them. :) 

I'm sorry if contributing to this project was not as straightforward as it should be; Contribution Guidelines are outdated and incomplete, and I'm currently in the process of reviewing and updating them, in a major effort to make contributing to the project easier.

Thank you again for your great work, and for the time you're dedicating to these blueprints!
I'm looking forward to seeing your contribution available to the public. :)

2021-12-06 08:26 UTC, krys1976 commented on blueprints/hooks/media_player/media_player.yaml
> +      prev_track: button_2_long
Good morning Matteo,

first of all, we all have a life outside the web, and I'm glad that you know had the time to review.

1. Controller naming

I totale agree that it should be like this. But this is a series of controllers, as on my research the all have the same behaviour, and on integration level, you would not be able to identify them as different controllers. In Philips Hue-App, they only have one entry, where you can choose of the type. See here for e.g.:

- ABB Smart Switch
- Busch-Jaeger smart light switch
- Eltako Smart Switch
- Feller Smart light control
- Jumitech Smart Switch
- JUNG Friends of Hue Switch
- Lutron Aurora
- Niko Dimmer Switch for Hue
- Nodon smart Switch. for Hue
- OPUS Friends of Hue Switch
- RetroTouch Friends of Hue Switch
- RunLessWire Click
- Sonic Friends of Hue Switch (the one I'm using as the perfectly fit into GIRA, having 6 Models)
- TCS hidden socket
- Vimar Friends of Hue Switch
- Voltus eVoToggle

All of them except the Lutron, are as far as I know integrated the same way in pyhue. All just identified as FoH which is Friends of Hue.

First we should check documentation of these products, but I guess the are all technical the same. If so I would prefer my already done naming, as this would match to all of them.

Best regards

Chris

2021-12-06 08:56 UTC, krys1976 commented on blueprints/hooks/cover/cover.yaml
> +      close_cover_tilt: button_4_long
See my comment at the end ...

2021-12-06 08:57 UTC, krys1976 commented on blueprints/hooks/light/light.yaml
> +            - Friends of Hue Right Switch
See my comment at the end ...  
Additionally this is the way how I implemented to use one (double) switch either as double switch or as the left/right part of it.

2021-12-06 08:58 UTC, krys1976 commented on blueprints/hooks/light/light.yaml
> +      brightness_down_repeat: button_4_long
See my comment at the end ...

2021-12-06 08:58 UTC, krys1976 commented on blueprints/hooks/media_player/media_player.yaml
> +            - Friends of Hue Double Switch
See my comment at the end ...

2021-12-06 08:59 UTC, krys1976 commented on blueprints/hooks/media_player/media_player.yaml
> +      prev_track: button_2_long
See my comment at the end ...

2021-12-06 09:16 UTC, krys1976 commented
Good Morning Matteo,

first of all, we all have a life outside the web. I'm glad that you found time to review my contribution now.

1. I totally agree with you, that we should follow this naming. But in this case, the Friends of Hue Controller is a collection of multiple devices, all having same behaviour. This is grounded to the implementation of pyhue.
They also show up in Philips Hue App as one item, but having to choose its commercial product:

- ABB Smart Switch
- Busch-Jaeger smart light switch
- Eltako Smart Switch
- Feller Smart light control
- Jumitech Smart Switch
- JUNG Friends of Hue Switch
- Lutron Aurora
- Niko Dimmer Switch for Hue
- Nodon smart switch for hue
- OPUS Friends of Hue Switch
- Retrotouch Friends of Hue Switch
- RunLessWire Click
- Senic Friends of Hue Switch (the one I use, but it has 6 different models)
- TCS hidden socket
- Vimar Friends of Hue Switch
- Voltus eVoToggle.

2021-12-06 21:33 UTC, EPMatt commented
Hi @krys1976,

thank you so much for your quick reply. I've applied some code suggestions similar to the ones you applied earlier today, leaving open what's left to discuss.

1. Thank you for providing the list of "Friends of Hue" devices. It's interesting that so many devices are grouped into a single item in the Hue app. However, I don't know whether different models from different manufacturers use the same mappings and events for their devices.
It might be interesting to investigate this point a little bit deeper before publishing the blueprint; in my opinion, user feedback regarding at least 1-2 models in addition to the ones you're using might be great. Having such approach would help us to identify the right naming for the controller blueprint, and for the controller model selection in hooks.
I'd like not to add unnecessary, duplicate blueprints for only slightly different devices. Instead, I'd prefer having one (or more, depending whether different models use all the same mappings) blueprint covering multiple devices. The [list of supported controllers](https://epmatt.github.io/awesome-ha-blueprints/docs/blueprints/controllers/) would then list all of the different available devices, linked to the same blueprint doc page. In my opinion the latter point is crucial, as we should avoid that users think their devices are not supported by our blueprints, just because not listed in the controllers list.
What do you think of this approach? Please let me know your thoughts about it. :) 

3-5. Great, I'll take care of these points regarding docs as soon as we're done with the blueprints. 👍🏻 

Thanks again!

2021-12-07 11:31 UTC, krys1976 commented
> 1. Thank you for providing the list of "Friends of Hue" devices. It's interesting that so many devices are grouped into a single item in the Hue app. However, I don't know whether different models from different manufacturers use the same mappings and events for their devices.

As I mentioned before, these controllers have all the same behaviour. This is related to the specs of that sample device and its implementation to pyhue. As we not map directly against the hardware, there will not be an other possibility.
A further investigation is not needed in my opinion.

And yes, we should list them all.

2021-12-07 22:20 UTC, EPMatt commented
Hi @krys1976,

thank you for your quick feedback.
> A further investigation is not needed in my opinion.

Ok, I agree with you that no testing is needed since they're all based on pyhue (didn't pay attention to that piece of information, so I thought it was only a nice way to group all of them in the Hue App).

> And yes, we should list them all. We could add this a second list to that controller page, or integrate into existing, listing them all, and mark them which are verified for working etc.

Great, I'd go for both adding them in the main list and creating a second list in the Friends of Hue Switch blueprint. 👍🏻
Marking which controllers are reported to be fully working is crucial.

Given our conclusion, I think we should call the blueprint `friends_of_hue` (`philips_friends_of_hue` sounds tricking to me, it might let users think that the blueprint is compatible with Philips devices only). What do you think?

Thanks again!

2021-12-09 07:09 UTC, krys1976 commented
> Great, I'd go for both adding them in the main list and creating a second list in the Friends of Hue Switch blueprint. 👍🏻
Marking which controllers are reported to be fully working is crucial.

I totally agree 

> Given our conclusion, I think we should call the blueprint `friends_of_hue` (`philips_friends_of_hue` sounds tricking to me, it might let users think that the blueprint is compatible with Philips devices only). What do you think?

I prefer friends_of_hue or friends_of_hue_family ... Philips_* would mislead users.

2021-12-23 10:29 UTC, krys1976 commented
Hi @EPMatt 

I was busy the past weeks, so I wasn't able to put effort into it.
Yesterday I noticed why my instance of home assistant had many problems with switches and lights.
So i fixed a problem regarding transitions first, and tomorrow morning I will have time to finalise the things here.

Cheers,
Chris

2022-08-07 18:14 UTC, Icki153 commented
Is there any update on this Enhancement?

2023-05-03 07:06 UTC, closed without merging