Update IKEA E1812 blueprint to support native controller double press
EPMatt/awesome-ha-blueprints pull request #228
Opened 2022-01-02 15:47 UTC by rschoultz

As IKEA introduced support of double-click in both E1812 and Gateway, I examined the actions sent by the E1812 and found that for Zigbee2MQTT this is treated as "off", and (from memory) in deCONZ as "1004".

Note on testing: This PR has so far ONLY been tested on:

- [ ] deCONZ
- [ ] ZHA
- [X] Zigbee2MQTT 

## Proposed change\*

1. Add support of native double-press events from IKEA E1812. 
2. At the same time, removing support of virtual double press events as these are redundant.
3. Following that, removed the need of the helper input text and user declaration of double-press support.

This likely closes #168 

## Checklist\*

- [X] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [X] I properly tested proposed changes on my system and confirm that they are working as expected.
- [-] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

2022-02-04 09:35 UTC, rschoultz commented
Hi @EPMatt,

I started this PR before having it tested, but of course should be going through that before it is accepted. I now got word that ZHA integration works, and I had tested Z2M, so 2/3 OK.

I also removed the code for storing double-click state as it is no longer needed. This might conflict with how you would like to develop this further, but my thought is that unused code and variables are a nuisance for maintenance. Though of course I may have overlooked something else in the ecosystem you built.

2022-02-16 22:49 UTC, EPMatt requested changes
Hi @rschoultz,

thank you so much for your precious contribution! I wasn't aware that IKEA added support for native double press clicks, that's such a cool feature. :) 

I requested a few changes on your contribution. Moreover, I also noticed that the CI is reporting some errors (I had to trigger it manually but I did some mess while doing it, so I had to force-push back your original changes :) ). Could you please fix the errors reported by the bots? You should be able to find more information in the PR's _Checks_ tab.

I'm aware that the current contribution workflow isn't as straightforward as it should be, hence if you have any doubts or questions don't hesitate to reach out to me here.

Thank you again for dedicating your precious time to the project and sorry again for my late response.

2022-02-16 22:49 UTC, EPMatt commented on blueprints/controllers/ikea_e1812/ikea_e1812.yaml
> +    Allows to optionally loop an action on a button long press as well as built-in double-click.
```suggestion
```

I'd remove this line. Since we don't have virtual double press anymore, I think is not required to add this line to the docs. What do you think about it?

2022-02-16 22:49 UTC, EPMatt commented on blueprints/controllers/ikea_e1812/ikea_e1812.yaml
> +    Controller automation for executing any kind of action triggered by the provided IKEA E1812 TRÅDFRI Shortcut button.
```suggestion
    Controller automation for executing any kind of action triggered by the provided IKEA E1812 TRÅDFRI Shortcut button. Allows to optionally loop an action on a button long press.
```
Keeping it as it was before the update.

2022-02-16 22:49 UTC, EPMatt commented on blueprints/controllers/ikea_e1812/ikea_e1812.yaml
>    # adjusted debounce delay so that the resulting double press delay is exactly as specified by the user when running the action, taking also account of debouncing
```suggestion
```
As the `adjusted_double_press_delay` input is no longer present, we can delete also these comments. :)

2022-02-16 22:49 UTC, EPMatt commented on blueprints/controllers/ikea_e1812/ikea_e1812.yaml
>    # make sure it never goes below the minimum double press delay
```suggestion
```
Same goes here. :)

2022-02-16 22:49 UTC, EPMatt commented on blueprints/controllers/ikea_e1812/ikea_e1812.yaml
> +      button_double: ['off']   # UNTESTED
```suggestion
      button_double: ['off']
```
Remove the untested label since we received positive feedback from a ZHA user.

2022-02-16 22:49 UTC, EPMatt commented on website/docs/blueprints/controllers/ikea_e1812.mdx
> +The blueprint also adds support for hardware double button press events, exposed by the controller itself.
```suggestion
```
In my opinion we could remove this line completely, as the blueprint supports all the hardware button events, not just double press ones. I'm afraid this line might be a little bit redundant with the blueprint description.

2022-02-16 22:49 UTC, EPMatt commented on blueprints/controllers/ikea_e1812/ikea_e1812.yaml
> -          domain: input_text
I'll add a note here which indeed refers to all the changes relative to the `helper_last_controller_event` input.
I totally agree with you that unused code should be removed, also to improve the blueprint's user experience. However, I'm planning to add support for additional advanced features (e.g. "hook channels", allowing the controller automation to route actions to different hooks) which would require such input.

I'm afraid that removing this input now, although totally logical, would instead require us to introduce a new breaking change in the future to reintroduce the same input.

Moreover, in my opinion it's also easier for users to think about all the controller blueprints having the same exact interface: `controller_entity` or `controller_device` (depending on the used integration), `integration` and `helper_last_controller_event` as required inputs.

What do you think about this solution?

2022-06-01 01:16 UTC, closed without merging