remove spaces to match new helper format in 2023.5
EPMatt/awesome-ha-blueprints pull request #545
Opened 2023-05-05 20:56 UTC by LordSushiPhoenix

Thank you for taking the time to work on a Pull Request. Your contribution is really appreciated! :tada:
**Please don't delete any part of the template**, since keeping the provided structure will help maintainers to review your work more rapidly.

Sections marked as \* are required and need to be filled in.

## Breaking change

If your PR contains a breaking change for existing users, it is important to describe what breaks, how to make it work again and why we did this. This section will be used to craft the changelog entry, after your PR gets approved and merged.

Note: Remove this section if this PR is NOT a breaking change.

## Proposed change\*

Describe the big picture of your changes here, and why your pull request should be accepted. If it fixes a bug or resolves a feature request, be sure to put `closes #XXXX` in this section to auto-close relevant issues.

Please note that for important and breaking changes it's always better to open an issue first for discussing the proposal.

Make sure to provide enough information so that your pull request can be reviewed.

The last controller event format has changed in 2023.5 and broken some controller automations. Removing spaces fixes it. Closes #544 

## Checklist\*

- [ ] I followed sections of the [Contribution Guidelines](https://github.com/EPMatt/awesome-ha-blueprints/blob/main/CONTRIBUTING.md) relevant to changes I'm proposing.
- [ ] I properly tested proposed changes on my system and confirm that they are working as expected.
- [ ] I formatted files with Prettier using the command `npm run format` before submitting my Pull Request.

2023-05-06 14:25 UTC, tumtumsback commented
I updated my ikea_e1743.yaml with this code, but still no dice.

2023-05-06 14:45 UTC, tumtumsback requested changes
Implemented this, but it did not solve the issue for me.

2023-05-08 04:08 UTC, LaPe63 commented
This change works for me on both of my systems, with E1743 controllers.

2023-05-13 15:26 UTC, tumtumsback commented
> This change works for me on both of my systems, with E1743 controllers.

LaPe63 what is your secret ... I've tried everything, I can't get double press events working on my E1743 remotes in 2023.5+

2023-05-15 13:16 UTC, LaPe63 commented
> > This change works for me on both of my systems, with E1743 controllers.
> 
> LaPe63 what is your secret ... I've tried everything, I can't get double press events working on my E1743 remotes in 2023.5+

Dont know, just made sure i had the latest version (2022.08.08) and then i edited the file directly under  /config/blueprints/automation/EPMatt/ and removed the spaces in 6 places, and restarted HA. I did the same on ikea_e2001_e2002, and it also worked.

2023-05-15 13:18 UTC, tumtumsback commented
> > > This change works for me on both of my systems, with E1743 controllers.
> > 
> > 
> > LaPe63 what is your secret ... I've tried everything, I can't get double press events working on my E1743 remotes in 2023.5+
> 
> Dont know, just made sure i had the latest version (2022.08.08) and then i edited the file directly under /config/blueprints/automation/EPMatt/ and removed the spaces in 6 places, and restarted HA. I did the same on ikea_e2001_e2002, and it also worked.

6 places? what do you mean by that ...

2023-05-15 13:21 UTC, LordSushiPhoenix commented
I'm using Z2M.

2023-05-15 13:24 UTC, tumtumsback commented
Hmm okay because my 1743s are joined via Deconz ... I wonder if there's something different there?

2023-05-15 13:25 UTC, LordSushiPhoenix commented
Possible, I've only ever used or tested Z2M. Does the string in your last event helper look like the ones in this comment? https://github.com/EPMatt/awesome-ha-blueprints/issues/544#issuecomment-1536593604

2023-05-15 13:32 UTC, tumtumsback commented
> Possibly, I've only ever used or tested Z2M. Does the string in your last event helper look like the ones in this comment? [#544 (comment)](https://github.com/EPMatt/awesome-ha-blueprints/issues/544#issuecomment-1536593604)

To test this, I'd have to snapshot (so I can rollback when doubletap breaks again), upgrade to 2023.5, and then test... I'll see what I can do later today.

2023-05-15 13:33 UTC, LordSushiPhoenix commented
If you grab the string on 2023.5 that would at least validate whether or not the new regex matches it without rolling back.

2023-05-15 13:39 UTC, tumtumsback commented
> If you grab the string on 2023.5 that would at least validate whether or not the new regex matches it without rolling back.

10-4 // and where exactly would I be looking for this string -- in the Deconz logs?

2023-05-15 14:02 UTC, LordSushiPhoenix commented
Right in home assistant, under the helpers tab. Find the input text helper used for the automation and copy the value.

2023-05-15 14:17 UTC, LaPe63 commented
> > > > This change works for me on both of my systems, with E1743 controllers.
> > > 
> > > 
> > > LaPe63 what is your secret ... I've tried everything, I can't get double press events working on my E1743 remotes in 2023.5+
> > 
> > 
> > Dont know, just made sure i had the latest version (2022.08.08) and then i edited the file directly under /config/blueprints/automation/EPMatt/ and removed the spaces in 6 places, and restarted HA. I did the same on ikea_e2001_e2002, and it also worked.
> 
> 6 places? what do you mean by that ...
I changed the line 280 and 281 to match the commit.
> 
> Also, what integration are you using -- Deconz, ZHA, or Z2M?
Z2M.

2023-05-15 18:21 UTC, tumtumsback commented
Before 2023.5:

Successful Fan turn off:

Text 1 changed to {"trigger_action": "double_press", "last_triggered": "2023-05-15 09:37:31.006032-04:00"} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'
9:37:31 AM - 5 hours ago
Text 1 changed to {"trigger_action": 2002, "last_triggered": "2023-05-15 09:37:31.000759-04:00"} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'
9:37:31 AM - 5 hours ago
Text 1 changed to {"trigger_action": 2002, "last_triggered": "2023-05-15 09:37:30.200153-04:00"} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'
9:37:30 AM - 5 hours ago

Successful Fan turn on:

Text 1 changed to {"trigger_action": "double_press", "last_triggered": "2023-05-15 09:37:26.105687-04:00"} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'
9:37:26 AM - 5 hours ago
Text 1 changed to {"trigger_action": 1002, "last_triggered": "2023-05-15 09:37:26.100899-04:00"} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'
9:37:26 AM - 5 hours ago
Text 1 changed to {"trigger_action": 1002, "last_triggered": "2023-05-15 09:37:25.300586-04:00"} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'
9:37:25 AM - 5 hours ago


After 2023.5:

Unsuccessful Fan turn on(s):

Double press attempt #2

Text 1 changed to {"a":1002,"t":1684174588.065661} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'
2:16:28 PM - 23 seconds ago
Text 1 changed to {"a":1002,"t":1684174587.465954} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'

Double press attempt #1

2:16:27 PM - 24 seconds ago
Text 1 changed to {"a":1002,"t":1684174583.114406} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'
2:16:23 PM - 28 seconds ago
Text 1 changed to {"a":1002,"t":1684174582.609161} triggered by automation Bathroom - Doubletap - Fan triggered by event 'deconz_event'

2023-05-15 18:24 UTC, tumtumsback commented
So from above, I upgraded to 2023.5, then replaced the YAML with the fixed YAML, then restarted HA completely, and that's what I get.

Before 2023.5, you can see after two "1002" events, it then successfully triggers the "double_press" action to turn on the Fan.

After 2023.5, you can see the two "1002" events, but a "double_press" action never follows. And, I see the "1002" events appear to be improperly crafted -- or, at least, don't look normal like they did before 2023.5

2023-05-15 19:10 UTC, LordSushiPhoenix commented
Assuming you were running the version of the blueprint yaml that's currently in `main`, I'm not sure why it works for you on 2022.4, but the yaml is trying to match the string `"a":".*"`, i.e. `"a":"1002"` but the deconz events are stored as `"a":1002`. This probably has something to do with it since there are no quote characters to match.

2023-05-15 19:12 UTC, tumtumsback commented
I was running an OLD version of the YAML. I implemented this blueprint well
over a year ago, so that explains the different syntax.

But, this doesn't explain why the blueprint isn't picking up on
double_press events...

On Mon, May 15, 2023 at 3:10 PM LordSushiPhoenix ***@***.***>
wrote:

> Assuming you were running the version of the blueprint yaml that's
> currently in main, I'm not sure why it works for you on 2022.4, but the
> yaml is trying to match the string "a":".*", i.e. "a":"1002" but the
> deconz events are stored as "a":1002. This probably has something to do
> with it since there are no quote characters to match.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EPMatt/awesome-ha-blueprints/pull/545#issuecomment-1548418750>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOBYVLJBPWBAANRWZCTACNLXGJ5SDANCNFSM6AAAAAAXXSP2Z4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-05-15 19:17 UTC, LordSushiPhoenix commented
> This probably has something to do with it since there are no quote characters to match.
try removing the escaped quotation marks around the `.*` in both lines.

2023-05-17 21:50 UTC, tumtumsback commented
> > This probably has something to do with it since there are no quote characters to match.
> 
> try removing the escaped quotation marks around the `.*` in both lines.
> 
> Edit: if your version of the yaml was old enough, it may also have been before the introduction of debouncing, you may need to play with the debounce and double press delay. FWIW a triple tap more reliably triggers the double tap action on both my e1743 and e2001 controllers when the double press delay is set to a sane value (double tap consistently triggers when it's set to 4000ms, but then you have to wait 4s for single press actions.)

HOLY FLIP!

I removed the escaped quotation marks as you had suggested and it fricken worked.

2023-05-17 21:51 UTC, tumtumsback commented
So I assume this YAML now needs to be updated again to fix the regex to work properly with deconz?

2023-05-24 19:26 UTC, anthonylavado commented
Just wanted to add that this fixed long press issues for me with ZHA. There is indeed a difference between how HASS 2023.4.x and older would parse the messages. The new message format omits the spaces in the helper text.

2023-06-12 21:35 UTC, larsmathuseck commented
Any updates on this PR? Waiting for this fix to be merged ✌️

2023-08-31 23:19 UTC, botrosco commented
This also fixes the E1744 indefinitely increasing/decreasing brightness levels

2023-09-03 20:44 UTC, arsenicks commented
> Any updates on this PR? Waiting for this fix to be merged ✌️

Witth 48PR currently waiting, I wouldn't bet on that. I'm not sure @EPMatt still maintain, he seems absent from this project for few months but he seems to be active on some of his other github repo so I don't know what's up.. It's not an easy job to maintain "big" projects, he might be exausted or anything.. It would just be nice to know what's happening so everybody can move on with a fork or he can nominate other member of the community to help I guess.

Someone has oppenned an issue asking if the repo is really unmaintained/dead, noreply yet.. ( [issue #554](https://github.com/EPMatt/awesome-ha-blueprints/issues/554) )

2023-09-13 12:56 UTC, collateral127 commented
> > > This probably has something to do with it since there are no quote characters to match.
> > 
> > 
> > try removing the escaped quotation marks around the `.*` in both lines.
> > Edit: if your version of the yaml was old enough, it may also have been before the introduction of debouncing, you may need to play with the debounce and double press delay. FWIW a triple tap more reliably triggers the double tap action on both my e1743 and e2001 controllers when the double press delay is set to a sane value (double tap consistently triggers when it's set to 4000ms, but then you have to wait 4s for single press actions.)
> 
> HOLY FLIP!
> 
> I removed the escaped quotation marks as you had suggested and it fricken worked.

if anyone is curious as to how you should structure that string for deconz, here it is:

`regex_match("^\{((\"a\":.*|\"t\":\d+\.\d+)(,)?){2}\}$"))`

not gonna lie, it took me far too long to work this out - i don't know regex very well, and was having trouble translating the words you were all speaking into regex that actually worked haha

2025-01-02 22:53 UTC, EPMatt approved these changes
LGTM. Thanks for your contribution - and for your patience -  @LordSushiPhoenix!

2025-01-02 22:56 UTC, EPMatt commented
Also, thanks everyone for your kind patience - life happens, and unfortunately I couldn't contribute at all to this project for a long time. Luckily, I'm hopefully now slowly getting back to be more active here.

Thank you all for your continuous support - can't believe we are getting close to 900 stars! Let's bring Awesome HA Blueprints back to life 🔥

2025-01-02 22:57 UTC, merged